server:
  port: 8761

spring:
  application:
    name: discoveryservice
  cloud:
     config:
       uri: http:127.0.0.1:8888
       name: ecommerce


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instacne_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
